# Site settings
title: Native Steamer Card
email: get@easynative.app
description: > # this means to ignore newlines until "baseurl:"
  Dynamic theme for streamer websites
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://themes.easynative.app/streamer" # the base hostname & protocol for your site
#twitter_username:
github_username: AppEasier

# Build settings
markdown: kramdown
